// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebGuider.Admin.Models.DBModel;

namespace WebGuider.Admin.Migrations
{
    [DbContext(typeof(WebGuideContext))]
    [Migration("20220623162826_thirdmigration")]
    partial class thirdmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebGuider.Admin.Models.DBModel.WebGuideInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Item_CanvasData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Classes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Sequence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebGuideInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
